import Head from 'next/head'
import Link from 'next/link'

import { externalSources } from "../constants/external-sources"
import styles from '../styles/home.module.css'

export default function RssTest() {
  return (
    <div className={styles.container}>
      <Head>
        <title>RSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {externalSources.map((source) => (
          <Link href={`/source/${source.slug}`} key={source.slug}>
            <a>{source.title}</a>
          </Link>
        ))}
      </main>
    </div>
  )
}
